### ISSUE TITLE
Allow setting reviewers when using github_pull_request

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#130]
I would like to be able to set the reviewers for PRs created through all-repos.

```sh
all-repos-sed ... --reviewers mycolleague
```

I was going to implement this as a custom push module, but currently push modules can only receive `Settings` and `branch_name`.

One approach would be to implement push strategies as classes with a hook for adding additional parser arguments. Something like:

```python
class GitHubPullRequest(BasePushStrategy):
    def add_arguments(self, parser: ParserType):
        parser.add_arguments("--reviewers", nargs="*")

   # or "def handle",  to match Django's management commands
    def __call__(self, settings: Settings, branch_name: str, parsed_args: Any) -> None:
        # ...
        resp = github_api.req(
            f"{settings.base_url}/repos/{repo_slug}/pulls",
            data=data,
            headers=headers,
            method="POST",
        )
        url = resp.json["url"]
        html_url = resp.json["html_url"]
        print(f"Pull request created at {html_url}")
        reviewers = parsed_args.reviewers
        if reviewers:
            resp = github_api.req(
                f"{url}/requested_reviewers",
                data=json.dumps({"reviewers": reviewers}).encode(),
                headers=headers,
                method="POST",
            )
            print(f"Requested review from {reviewers}")
```

The `"push"` config in `all-repos.json` would point to these classes instead of modules.

```json
{
  "push": "all_repos.push.GitHubPullRequest"
}
```

Open questions:

1. Is the above interface a good idea?
  1a. If so, is it OK to implement it as a breaking change?
2. Should the "reviewer" functionality be included in all-repos core?

I don't have a strong feeling on 2. As long as there's a way to do it, I'm fine keeping it as custom code outside of core to start.  Up to you, @asottile

**Comment by asottile** [comment]
the current interface is designed such that everything is static and stateless (this is why I chose modules instead of classes, to avoid the gravitation towards over-DRY inheritance that tends to happen even with the simplest of class hierarchies).  I do not want classes so the idea of that is out (plus you'd probably want to do `mod.name:attr` such that it could be unambiguous where the module ends and the class begins in the case of nested classes, etc.)

reviewers is right on the fringe of things that I think would make sense, hmm -- maybe it should be added to all push modules?  then again, the way we handled reviewers when running these at lyft was only after all-repos ran 🤔

**Comment by sloria** [comment]
> then again, the way we handled reviewers when running these at lyft was only after all-repos ran 

Can you clarify this? How did you assign a given reviewer to all the PRs for an all-repos run?

**Comment by asottile** [comment]
I wrote a special `push` module which looked at the owner (in lyft's case this was a slack channel in a yaml file inside the repository being modified) of the repository and left a comment after PR creation (lyft's PR lifecycle is done through emoji / github comments / chat bot commands)

**Comment by asottile** [comment]
(don't have access to the code any more though, sorry -- got laid off last week)

**Comment by sloria** [comment]
OK, I see. We use "Reviewers" on GitHub--we don't use an owners file or anything like that.

If classes are out of the question, then I suppose we could achieve something similar at the module level:

```python
# Optional for modules to define this
def add_arguments(parser: ParserType) -> None:

def push(settings: Settings, branch_name: str, parsed_args: Any) -> None:
```

Seems better than passing `reviewers` to all push modules. It's not relevant for `merge_to_master`. Also, the above opens the door for users to implement support for other GH features (labels, assignees, etc). 

What do you think?

**Comment by asottile** [comment]
my concern is it increases the api surface a lot and it would be breaking.  exposing an argument parser is also tricky since it constricts how the tool itself can grow over time (since it now needs to worry about colliding with plugins, many of which it cannot see).  (from maintaining flake8 / pytest I've seen this break way too many times and it's especially frustrating for powerless users but annoying for both plugin maintainers and the framework maintainer)

it may make more sense to configure these things in the particular plugins (config files, environment variables, etc. come to mind as alternative ways to accomplish this)

**Comment by sloria** [comment]
Fair enough--I can see how allowing plugins to define their own arguments could open Pandora's Box.

> it may make more sense to configure these things in the particular plugins (config files, environment variables, etc. come to mind as alternative ways to accomplish this)

Sure, this seems workable. With https://github.com/asottile/all-repos/pull/132 , I'd be able to do something like

```python
# github_pull_request_with_reviewers.py
from all_repos.push.github_pull_request import make_pull_request

def push(...):
    resp = make_pull_request(settings, branch_name)
    reviewers = os.environ.get('GH_REVIEWERS', '').split(',')
    if reviewers:
        url = resp.json['url']
        resp = github_api.req(
            f"{url}/requested_reviewers",
            data=json.dumps({"reviewers": reviewers}).encode(),
            headers=headers,
            method="POST",
        )
```

**Comment by asottile** [comment]
I release 1.18 for ya by the way 🎉

**Comment by sloria** [comment]
tyvm!

**Comment by sloria** [comment]
@asottile Oops, looks like 1.18 isn't on PyPI . Can you publish that when you have a moment?

![Image 2020-05-08 at 4 08 48 PM](https://user-images.githubusercontent.com/2379650/81445090-45064b00-9146-11ea-889b-a13f027e3bfb.png)

**Comment by asottile** [comment]
should be there now, my b

**Comment by sloria** [comment]
thanks!
