### ISSUE TITLE
How could I select github repos by topic?

### ISSUE THREAD

**Issue by pkaeding** [asottile/all-repos#203]
In my org, we make heavy use of ['topics'](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to categorize repositories. These categories are not always encoded in the repo name (eg, the language or platform might be added as a topic, or a topic might indicate that a repo is part of the main service, versus a maintenance tool, etc). 

How might I select certain repos, to be able to operate on all repos with a specific topic, etc? Could the `include`/`exclude` regexes be used here? The README makes it sound like the regex is only applied to the repo name (but maybe I misunderstood)?

Or maybe a custom source is the way to go? Do you have any examples of this?

Re: https://github.com/asottile/all-repos/pull/202

**Comment by asottile** [comment]
if the repository names are constant you can generate a list and use that in your configuration

otherwise a custom source is the way to go -- there's nothing special about a "custom" source compared to the actual sources -- they work the same https://github.com/asottile/all-repos#writing-your-own-source
