### ISSUE TITLE
Provide a way to blacklist or whitelist which pre-commit hooks to autoupdate

### ISSUE THREAD

**Issue by ealter** [asottile/all-repos#61]
We have a pre-commit hook which requires manual intervention when bumping. If I'm running `pre-commit autoupdate` across may repositories, I would like to exclude that repository. `pre-commit autoupdate` already supports a `--repo` option which allows us to whitelist repositories.

Can we expose that option in the autopep8-wrapper auto-fixer?

**Comment by asottile** [comment]
Sounds like the hook that requires manual intervention is poorly designed -- I don't really want to bend over backward to try and support a broken hook.  Plus, `--repo` would be insufficient since you want _exclusion_ not _inclusion_.

Basically, I'm inclined to say: fix the broken hook, don't complicate the world.
