### ISSUE TITLE
Support interactive cloning

### ISSUE THREAD

**Issue by mitzkia** [asottile/all-repos#88]
Hi, could you imagine a feature where selecting repositories (for cloning) could be interactive?
My use-case is when filtering from lot of repositories is not trivial (can not decide easily with collaborator/fork/private true-false options).
Found a python module for this: **PyInquirer -> checkbox type**

1, example all-repos.json:
```
    ...
    "source_settings":  {
        "api_key": "...",
        "username": "username",
    	"interactive": true,
        "other-options": ....
    },
    ...
```

2, In this case `all-repos-clone` should offer interactive selection for all repositories related to options: collaborator/fork/private

3, Selection:
```
= Organization1 =
[] repository1 (collaborator or fork or private) 
[] repository2 (collaborator or fork or private) 
[] repository3 (collaborator or fork or private) 
= Organization2 =
[] repository4 (collaborator or fork or private) 
[] repository5 (collaborator or fork or private) 
[] repository6 (collaborator or fork or private) 
```
4, Only the selected repositories will be cloned

**Comment by mitzkia** [comment]
I do not want to increase the scope of existing cloning feature. My feeling is this feature can be increase it later. What I mean, maybe someone wants to see in checkboxes which repositories are already cloned.

```
= Organization1 =
[X] repository1 (collaborator or fork or private) ---> already cloned 
[] repository2 (collaborator or fork or private)  ---> not yet cloned
[X] repository3 (collaborator or fork or private)  ---> already cloned
``` 

So I understand if you do not want to increase the scope of `all-repos-clone` in this way.

**Comment by asottile** [comment]
I *think* the [`json_file` source](https://github.com/asottile/all-repos#all_repossourcejson_file) satisfies what you're looking for

A sample workflow:

1. set up using `github` source + `all-repos-clone` (can even `exclude: ''` to make it not clone anything)
2. `mv {outputdir}/repos.json .` (there's also a `repos_filtered.json` which includes just the narrowed things)
3. edit `repos.json` to contain exactly what you do want
4. switch to the `json_file` source

---

I'm not sure interactive would work, or at least it wouldn't work as you've described (since that would only apply to the github source).  `all-repos-clone` is also intended to be non-interactive so you can run it with `cron` or whatever.  It's also cloning in parallel so I don't think interactive would work with that either.  🤔

**Comment by mitzkia** [comment]
Hi, 
Thanks for your explanation and for the suggestion with json_file source. It worked for me.
It is something like I expect with interactive clone, just with several more steps, so it is ok for me.
